PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^TermInfo/', include('apps.TermInfo.urls', namespace='TermInfo')),  # 学期信息模块
    url(r'^ClassInfo/', include('apps.ClassInfo.urls', namespace='ClassInfo')),  # 班级信息模块
    url(r'^Student/', include('apps.Student.urls', namespace='Student')),  # 学生信息模块
    url(r'^Course/', include('apps.Course.urls', namespace='Course')),  # 课程信息模块
    url(r'^ScoreInfo/', include('apps.ScoreInfo.urls', namespace='ScoreInfo')),  # 成绩信息模块
    url(r'^Attendance/', include('apps.Attendance.urls', namespace='Attendance')),  # 学生点名模块
    url(r'^TimeInfo/', include('apps.TimeInfo.urls', namespace='TimeInfo')),  # 学时信息模块
    url(r'^AttendanceState/', include('apps.AttendanceState.urls', namespace='AttendanceState')),  # 出勤状态模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/TimeInfo/urls.py
from apps.TimeInfo.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'TimeInfo'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<timeInfoId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<timeInfoId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<timeInfoId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<timeInfoId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/TimeInfo/models.py
from django.db import models


class TimeInfo(models.Model):
    timeInfoId = models.AutoField(primary_key=True, verbose_name='记录编号')
    timeInfoName = models.CharField(max_length=20, default='', verbose_name='学时名称')

    class Meta:
        db_table = 't_TimeInfo'
        verbose_name = '学时信息信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        timeInfo = {
            'timeInfoId': self.timeInfoId,
            'timeInfoName': self.timeInfoName,
        }
        return timeInfo


PythonProject/apps/TimeInfo/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.TimeInfo.models import TimeInfo
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台学时信息添加
    def get(self,request):

        # 使用模板
        return render(request, 'TimeInfo/timeInfo_frontAdd.html')

    def post(self, request):
        timeInfo = TimeInfo() # 新建一个学时信息对象然后获取参数
        timeInfo.timeInfoName = request.POST.get('timeInfo.timeInfoName')
        timeInfo.save() # 保存学时信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改学时信息
    def get(self, request, timeInfoId):
        context = {'timeInfoId': timeInfoId}
        return render(request, 'TimeInfo/timeInfo_frontModify.html', context)


class FrontListView(BaseView):  # 前台学时信息查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        # 然后条件组合查询过滤
        timeInfos = TimeInfo.objects.all()
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(timeInfos, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        timeInfos_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'timeInfos_page': timeInfos_page,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'TimeInfo/timeInfo_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示学时信息详情页
    def get(self, request, timeInfoId):
        # 查询需要显示的学时信息对象
        timeInfo = TimeInfo.objects.get(timeInfoId=timeInfoId)
        context = {
            'timeInfo': timeInfo
        }
        # 渲染模板显示
        return render(request, 'TimeInfo/timeInfo_frontshow.html', context)


class ListAllView(View): # 前台查询所有学时信息
    def get(self,request):
        timeInfos = TimeInfo.objects.all()
        timeInfoList = []
        for timeInfo in timeInfos:
            timeInfoObj = {
                'timeInfoId': timeInfo.timeInfoId,
                'timeInfoName': timeInfo.timeInfoName,
            }
            timeInfoList.append(timeInfoObj)
        return JsonResponse(timeInfoList, safe=False)


class UpdateView(BaseView):  # Ajax方式学时信息更新
    def get(self, request, timeInfoId):
        # GET方式请求查询学时信息对象并返回学时信息json格式
        timeInfo = TimeInfo.objects.get(timeInfoId=timeInfoId)
        return JsonResponse(timeInfo.getJsonObj())

    def post(self, request, timeInfoId):
        # POST方式提交学时信息修改信息更新到数据库
        timeInfo = TimeInfo.objects.get(timeInfoId=timeInfoId)
        timeInfo.timeInfoName = request.POST.get('timeInfo.timeInfoName')
        timeInfo.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台学时信息添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'TimeInfo/timeInfo_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        timeInfo = TimeInfo() # 新建一个学时信息对象然后获取参数
        timeInfo.timeInfoName = request.POST.get('timeInfo.timeInfoName')
        timeInfo.save() # 保存学时信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新学时信息
    def get(self, request, timeInfoId):
        context = {'timeInfoId': timeInfoId}
        return render(request, 'TimeInfo/timeInfo_modify.html', context)


class ListView(BaseView):  # 后台学时信息列表
    def get(self, request):
        # 使用模板
        return render(request, 'TimeInfo/timeInfo_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        # 然后条件组合查询过滤
        timeInfos = TimeInfo.objects.all()
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(timeInfos, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        timeInfos_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        timeInfoList = []
        for timeInfo in timeInfos_page:
            timeInfo = timeInfo.getJsonObj()
            timeInfoList.append(timeInfo)
        # 构造模板页面需要的参数
        timeInfo_res = {
            'rows': timeInfoList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(timeInfo_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除学时信息信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        timeInfoIds = self.getStrParam(request, 'timeInfoIds')
        timeInfoIds = timeInfoIds.split(',')
        count = 0
        try:
            for timeInfoId in timeInfoIds:
                TimeInfo.objects.get(timeInfoId=timeInfoId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出学时信息信息到excel并下载
    def get(self, request):
        # 收集查询参数
        # 然后条件组合查询过滤
        timeInfos = TimeInfo.objects.all()
        #将查询结果集转换成列表
        timeInfoList = []
        for timeInfo in timeInfos:
            timeInfo = timeInfo.getJsonObj()
            timeInfoList.append(timeInfo)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(timeInfoList)
        # 设置要导入到excel的列
        columns_map = {
            'timeInfoId': '记录编号',
            'timeInfoName': '学时名称',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'timeInfos.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="timeInfos.xlsx"'
        return response


PythonProject/templates/TimeInfo/timeInfo_add.html
{% include 'check_logstate.html' %}
{% load staticfiles %}

 <link rel="stylesheet" type="text/css" href="{% static 'css/timeInfo.css' %}" />
<div id="timeInfoAddDiv">
    {% csrf_token %}
	<form id="timeInfoAddForm" enctype="multipart/form-data"  method="post">
		<div>
			<span class="label">学时名称:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="timeInfo_timeInfoName" name="timeInfo.timeInfoName" style="width:200px" />

			</span>

		</div>
		<div class="operation">
			<a id="timeInfoAddButton" class="easyui-linkbutton">添加</a>
			<a id="timeInfoClearButton" class="easyui-linkbutton">重填</a>
		</div> 
	</form>
</div>
<script src="{% static 'js/TimeInfo/timeInfo_add.js' %}"></script>

PythonProject/templates/TimeInfo/timeInfo_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>学时信息添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
{% include 'header.html' %}
<div class="container">
	<div class="row">
		<div class="col-md-12 wow fadeInUp" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li role="presentation" ><a href="{% url 'TimeInfo:frontList' %}">学时信息列表</a></li>
			    	<li role="presentation" class="active"><a href="#timeInfoAdd" aria-controls="timeInfoAdd" role="tab" data-toggle="tab">添加学时信息</a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
				    <div role="tabpanel" class="tab-pane" id="timeInfoList">
				    </div>
				    <div role="tabpanel" class="tab-pane active" id="timeInfoAdd"> 
				      	<form class="form-horizontal" name="timeInfoAddForm" id="timeInfoAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
						  <div class="form-group">
						  	 <label for="timeInfo_timeInfoName" class="col-md-2 text-right">学时名称:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="timeInfo_timeInfoName" name="timeInfo.timeInfoName" class="form-control" placeholder="请输入学时名称">
							 </div>
						  </div>
				          <div class="form-group">
				             <span class="col-md-2""></span>
				             <span onclick="ajaxTimeInfoAdd();" class="btn btn-primary bottom5 top5">添加</span>
				          </div>
						</form> 
				        <style>#timeInfoAddForm .form-group {margin:10px;}  </style>
					</div>
				</div>
			</div>
		</div>
	</div> 
</div>

{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script>
	//提交添加学时信息信息
	function ajaxTimeInfoAdd() { 
		//提交之前先验证表单
		$("#timeInfoAddForm").data('bootstrapValidator').validate();
		if(!$("#timeInfoAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'TimeInfo:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#timeInfoAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证学时信息添加表单字段
	$('#timeInfoAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"timeInfo.timeInfoName": {
				validators: {
					notEmpty: {
						message: "学时名称不能为空",
					}
				}
			},
		}
	}); 
})
</script>
</body>
</html>

PythonProject/templates/TimeInfo/timeInfo_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>学时信息查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div style="display:none;">
		<div class="page-header">
    		<h1>学时信息查询</h1>
		</div>
		<form name="timeInfoQueryForm" id="timeInfoQueryForm" action="{% url 'TimeInfo:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#timeInfoListPanel" aria-controls="timeInfoListPanel" role="tab" data-toggle="tab">学时信息列表</a></li>
			    	<li role="presentation" ><a href="{% url 'TimeInfo:frontAdd' %}" style="display:none;">添加学时信息</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="timeInfoListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>记录编号</td><td>学时名称</td><td>操作</td></tr>
                                        {% for timeInfo in timeInfos_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ timeInfo.timeInfoId }}</td>
 											<td>{{ timeInfo.timeInfoName }}</td>
 											<td>
 												<a href="{% url 'TimeInfo:frontShow' timeInfo.timeInfoId  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="timeInfoEdit('{{ timeInfo.timeInfoId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="timeInfoDelete('{{ timeInfo.timeInfoId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }}> 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="timeInfoEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;学时信息信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="timeInfoEditForm" id="timeInfoEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="timeInfo_timeInfoId_edit" class="col-md-3 text-right">记录编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="timeInfo_timeInfoId_edit" name="timeInfo.timeInfoId" class="form-control" placeholder="请输入记录编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="timeInfo_timeInfoName_edit" class="col-md-3 text-right">学时名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="timeInfo_timeInfoName_edit" name="timeInfo.timeInfoName" class="form-control" placeholder="请输入学时名称">
			 </div>
		  </div>
		</form> 
	    <style>#timeInfoEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxTimeInfoModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.timeInfoQueryForm.currentPage.value = currentPage;
    document.timeInfoQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.timeInfoQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.timeInfoQueryForm.currentPage.value = pageValue;
    documenttimeInfoQueryForm.submit();
}

/*弹出修改学时信息界面并初始化数据*/
function timeInfoEdit(timeInfoId) {
	$.ajax({
		url :  '/TimeInfo/update/' + timeInfoId,
		type : "get",
		dataType: "json",
		success : function (timeInfo, response, status) {
			if (timeInfo) {
				$("#timeInfo_timeInfoId_edit").val(timeInfo.timeInfoId);
				$("#timeInfo_timeInfoName_edit").val(timeInfo.timeInfoName);
				$('#timeInfoEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除学时信息信息*/
function timeInfoDelete(timeInfoId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/TimeInfo/deletes",
			data : {
				timeInfoIds : timeInfoId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#timeInfoQueryForm").submit();
					//location.href= basePath + "TimeInfo/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交学时信息信息表单给服务器端修改*/
function ajaxTimeInfoModify() {
	$.ajax({
		url :   '/TimeInfo/update/' + $("#timeInfo_timeInfoId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#timeInfoEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                location.href= basePath + "TimeInfo/frontlist";
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

})
</script>
</body>
</html>


PythonProject/templates/TimeInfo/timeInfo_modify.html
{% load staticfiles %}
{% include 'check_logstate.html' %}
<link rel="stylesheet" type="text/css" href="{% static 'css/timeInfo.css' %}" />
<div id="timeInfo_EditDiv">
	<form id="timeInfoModifyForm" enctype="multipart/form-data"  method="post">
        {% csrf_token %}
		<div>
			<span class="label">记录编号:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="timeInfo_timeInfoId_modify" name="timeInfo.timeInfoId" value="{{ timeInfoId }}" style="width:200px" />
			</span>
		</div>

		<div>
			<span class="label">学时名称:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="timeInfo_timeInfoName_modify" name="timeInfo.timeInfoName" style="width:200px" />

			</span>

		</div>
		<div class="operation">
			<a id="timeInfoModifyButton" class="easyui-linkbutton">更新</a> 
		</div>
	</form>
</div>
<script src="{% static 'js/TimeInfo/timeInfo_modify.js' %}"></script>